# Copyright The Cloud Custodian Authors.
# SPDX-License-Identifier: Apache-2.0

"""
Oracle Cloud Infrastructure Authentication
"""
ENV_FINGERPRINT = "OCI_FINGERPRINT"
ENV_KEY_FILE = "OCI_KEY_FILE"
ENV_REGION = "OCI_REGION"
ENV_TENANCY = "OCI_TENANCY"
ENV_USER = "OCI_USER"
COMPARTMENT_IDS = "OCI_COMPARTMENTS"
DEFAULT_PROFILE = "DEFAULT"
STORAGE_NAMESPACE = "namespace_name"
PROFILE = "profile"
OCI_LOG_COMPARTMENT_ID = "OCI_LOG_COMPARTMENT_ID"
